# Generated by Django 4.2.2 on 2024-09-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300)),
                ('configurations', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LapImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='Laptop_images')),
                ('image_name', models.CharField(max_length=50)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drfviews.laptop')),
            ],
        ),
    ]
